name: Publish blog stats

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: '05 12 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Chicago"
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: logs-tarball
          if_no_artifact_found: warn

      - name: Extract logs
        run: |
          #!/bin/bash
          if [ -e logs.tar.zst ]; then
            zstd -d --rm logs.tar.zst
            tar -xf logs.tar
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::911986281031:role/github-actions-thetanerd.com-stats
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Create directories
        run: mkdir -p logs public

      - name: Download log files
        run: aws s3 sync --size-only s3://thetanerd.com-logs/ logs/

      - name: Install goaccess
        run: |
          wget -O - https://deb.goaccess.io/gnugpg.key | gpg --dearmor \
              | sudo tee /usr/share/keyrings/goaccess.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/goaccess.gpg arch=$(dpkg --print-architecture)] https://deb.goaccess.io/ $(lsb_release -cs) main" \
              | sudo tee /etc/apt/sources.list.d/goaccess.list
          sudo apt-get -q update
          sudo apt-get -q install -y goaccess

      - name: Run goaccess
        run: |
          find logs -name "*.gz" | \
            xargs zcat | \
            grep -v '/ghost' | \
            goaccess - \
              --log-format CLOUDFRONT \
              --date-format CLOUDFRONT \
              --time-format CLOUDFRONT \
              --agent-list \
              --ignore-status=301 \
              --ignore-status=302 \
              --ignore-crawlers \
              --anonymize-ip \
              --http-protocol=no \
              --http-method=no \
              --no-query-string \
              --output public/index.html

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Create log tarball
        run: |
          tar -cf logs.tar logs
          zstd --rm -T0 logs.tar

      - name: Store log tarball in artifact
        uses: actions/upload-artifact@v3
        with:
          name: logs-tarball
          path: logs.tar.zst

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
